- [A propos](index.md)
- [Portefeuilles - Les bases](wallets.md)
  - [Types de portefeuilles](Wallets/types.md)
  - [List de portefeuilles](Wallets/list.md)
  - [Yoroi](Wallets/Yoroi/yoroi.md)
    - [Installer/Désinstaller](Wallets/Yoroi/yoroi.md#install)
    - [Créer un nouveau portefeuille (Shelley)](Wallets/Yoroi/create.md)
    - [Restaurer un portefeuille existant (Shelley)](Wallets/Yoroi/restore.md)
    - [Récupérer/Transférer à partir d'un portefeuille Byron/ITN](Wallets/Yoroi/transfer.md)
  - [Ledger](ledger.md)
- [Exploreurs](explorers.md)
- [Choisir un pool pour délégation](select-pool-to-delegate.md)
- [Protégez-vous des escrocs](no-to-scam.md)

<details>
<summary>To - Do </summary>
> - [Not Started yet](index.md)
  - [Wallets](wallets.md)
    - [Daedalus](Wallets/daedalus.md)
      - [Versions and Platforms](Wallets/Daedalus/versions.md)
      - [How to Install/Upgrade](Wallets/Daedalus/install.md)
      - [Create a new Wallet](Wallets/Daedalus/create.md)
      - [Restore an existing Wallet](Wallets/Daedalus/restore.md)
      - [Delegating to a pool](Wallets/Daedalus/delegate.md)
      - [Upgrading Daedalus wallet](Wallets/Daedalus/upgrade.md)
      - [Queries/Known Issues](Wallets/Daedalus/issues.md)
        - [Access Denied during install](Wallets/Daedalus/issues.md)
        - [An error occurred while sending funds](Wallets/Daedalus/issues.md)
        - [Cardano Node Crashed upon launch](Wallets/Daedalus/issues.md)
        - [CPU Utilisation too high](Wallets/Daedalus/issues.md)
    - [Yoroi](Wallets/yoroi.md)
      - [Integration with Ledger](Wallets/Yoroi/ledger.md)
      - [Queries/Known Issues](Wallets/Yoroi/FAQ.md)
        - [Ledger connection stuck on "waiting for Commands.."](Wallets/Yoroi/FAQ.md#issues)
        - [Balance is incorrect in Yoroi interface](Wallets/Yoroi/FAQ.md#resync)
        - [Emergency Workarounds](Wallets/Yoroi/FAQ.md#workarounds)
  - [Other Community Contributions](community-contrib.md)
    - [Pooltool](Community/pooltool.md)
    - [CNTools](Community/cntools.md)
    - [Rewards Bot](Community/rewardsbot.md)
    - [Community Hosted Wiki](Community/wiki.md)
      - [Mind Map of cardano components](Community/wiki.md)
  - [Appendix](index.md)
  - [Contributors](Contributors.md)
</details>
